148 unlink categories
pax-app/Pax_Category pull request #2
Opened 2019-10-03 19:45 UTC by FabianaRibas

# Descrição
Nesta issue foram feitas:

- Conexão do banco com a models do Provider category e do General category;
-  Definição de rotas das consultas(GET)do json na views.py;
- É possivel testar mandando uma requisição pelo postman(rotas foram salvas na collection Category do postman ).

# Issue Relacionada

resolve #148

# Tipo de Mudanças

- [x] História de Usuário
- [ ] Historia Técnica
- [ ] Wiki

# Responsáveis pela revisão

@esiofreitas (PO)
@lucasdutraf (PO)

2019-10-04 00:17 UTC, lucasdutraf requested changes
Então, Fabi, infelizmente não tem como aceitar o PR. Por que primeiramente, algo prévio deveria ser feito para o seu poder acontecer, isso seria a US17, que teoricamente nela é onde seria configuradas as categorias relacionadas ao provedor de serviços. 

Logo, se não tem relacionamento das tags não tem como desvinculá-las (_que é o propósito da issue_),  mas de brinde você já fez o back da US27! Parabéns pelo trabalho de qualquer maneira, Fabi!

2019-10-09 03:14 UTC, lucasdutraf commented
Desde as mudanças requeridas foram adicionadas as seguintes funções:
* Estabelecimento de uma relação entre PROVIDER e PROVIDER_CATEGORY
* Quebra do relacionamento entre PROVIDER e PROVIDER_CATEGORY
* Listagem de todas as PROVIDER_CATEGORY de uma GENERAL_CATEGORY em específico

2019-10-09 03:17 UTC, lucasdutraf approved these changes

2019-10-09 03:20 UTC, lucasdutraf commented
Esse pull request também contempla o back-end da pax-app/Wiki#162

2019-10-09 05:56 UTC, rogerioo reviewed
Belo pythês migo! Ficou ótimo :heart:

2019-10-09 05:56 UTC, rogerioo commented
Parabens ao envolvidos! :smile: :heart_decoration:

2019-10-09 05:57 UTC, merged